#!/bin/sh

#Setting 90 Day Password Expiration in EC

#set Variables
loggedInUser=`python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");'`
expireDays=$(defaults read /Users/$loggedInUser/Library/Preferences/com.apple.Enterprise-Connect passwordExpireOverride)
checkKey=""



function keyCheck {
	checkKey=$(defaults read /Users/$loggedInUser/Library/Preferences/com.apple.Enterprise-Connect passwordExpireOverride)
}

# Run check to see if 90 Day key needs to be written
	
	if [[ "$expireDays" == 90 ]]; then
		echo "Key is already set to 90 Days"
		echo "Exiting now"
		exit 0
	else
	    echo "Lets Kill EC"
	    killall "Enterprise Connect"
	    sleep 3
		echo "Key is NOT Set!"
		echo "Let me set the key now"
		echo "$loggedInUser"
		sudo defaults write /Users/$loggedInUser/Library/Preferences/com.apple.Enterprise-Connect passwordExpireOverride -string 90
		sleep 3
		keyCheck
		echo "Let check the key value: $checkKey"
		sleep 5
		open -a "Enterprise Connect"
		echo "Done" >> /var/log/jamf.log
		exit 0
	fi
	
	
	